name: Deploy staging branch to FTP
on:
  push:
    branches: [ staging ]

concurrency:
  group: 'staging'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging
        fetch-depth: 2

    - uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ vars.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./
        REMOTE_DIR: ${{ vars.REMOTE_STAGING_DIR }}
        ARGS: --exclude-glob=.git*/**

